import Header from "@/components/Header";
import "./globals.css";
import { Inter  } from 'next/font/google'
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Footer from "@/components/Footer";
import { AuthProvider } from "./context/AuthContext";
const inter  = Inter ({
  subsets: ['latin'],
  variable: '--font-inter ',
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],

})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        <Header />
        <StairTransition />
        <PageTransition>
          <AuthProvider>{children}</AuthProvider></PageTransition>
      <Footer />

      </body>
    </html>
  );
}
